language: node_js
node_js:
  - "6"

before_install:
  - sudo apt-get update
  - sudo apt-get install git-all

install:
  - npm install
  - npm install forever -g
  - npm install -g flightplan

script:
  - export NODE_ENV=production
  - export WWW_WANGYN_NET_PORT=8000
  - forever start ./bin/www
  - npm test

#before_deploy:
#  - forever stop ./bin/www

deploy:
  - scp -r ./ spray@45.32.251.237:~/www.wangyn.net-node

#after_script:
#