language: node_js
node_js:
  - "6"

install:
  - npm install
  - npm install forever -g

script:
  - forever start ./bin/www
  - npm test


deploy:
  - scp -r ./ spray@45.32.251.237:~/www.wangyn.net-node

